# Generated by Django 4.2.7 on 2023-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/'),
        ),
    ]
